packages:
    - "apps/*"

minimumReleaseAge: 0
minimumReleaseAgeStrict: false
minimumReleaseAgeExclude:
  - '*'

allowBuilds:
    "@parcel/watcher": true
    esbuild: true
    sharp: true
    "@tailwindcss/oxide": true
